### ISSUE TITLE
writeAppend will truncate the data if file exists

### ISSUE THREAD

**Issue by xiongjiwei** [beyondstorage/go-service-fs#59]
`writeAppend` in `fs` will call `createFile`
https://github.com/beyondstorage/go-service-fs/blob/691613b2db2c2defc7d7b27e49faf06c3b4b4490/storage.go#L320-L321
which open the file with `O_CREATE|O_TRUNC`
https://github.com/beyondstorage/go-service-fs/blob/691613b2db2c2defc7d7b27e49faf06c3b4b4490/utils.go#L152-L156
it will truncate the data if file exists

**Comment by Xuanwo** [comment]
This issue points out two problems:

- [ ] go-service-fs `writeAppend` behavior is incorrect.
- [ ] go-integration-test should add a test in which we `writeAppend` twice and make sure they work correctly.

**Comment by Xuanwo** [comment]
@xiongjiwei Would you like to take the time to look at these two questions?

**Comment by xiongjiwei** [comment]
> @xiongjiwei Would you like to take the time to look at these two questions?

no problem, I will fix it and add the test.

**Comment by Xuanwo** [comment]
Fixed in #60
