### ISSUE TITLE
Stat returns error when path is a symlink that point to a non-existent file

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-service-fs#62]
`filepath.EvalSymlinks(path)` will return `lstat xxxxx: no such file or directory` if path is a symlink and points to a non-existent file or directory.

Maybe we can use `os.Readlink(name)` instead as it can get the destination of the named symbolic link even if the target is not exist?

**Comment by Xuanwo** [comment]
LGTM, but `Readlink` only read once, we need to handle multiple links.

**Comment by JinnyYi** [comment]
> LGTM, but `Readlink` only read once, we need to handle multiple links.

How about use `EvalSymlinks` first? If we get the target not exist related error from `EvalSymlinks`, then we use `Readlink` to try to get the target.

**Comment by Xuanwo** [comment]
`EvalSymlinks` calls `Readlink` internally,  this will add extra cost for it.

Maybe we can implement ourself `EvalSymlinks`: https://golang.org/src/path/filepath/symlink.go

**Comment by JinnyYi** [comment]
Fixed in https://github.com/beyondstorage/go-service-fs/pull/64
