### ISSUE TITLE
Lack of `WorkDir` evaluation during initialization

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-service-fs#65]
`WorkDir` passed in may be a symlink. We should set `WorkDir` to the path name after the evaluation of any symbolic links to ensure workdir is valid.

**Comment by JinnyYi** [comment]
@abyss-w can you help to fix the issue as discussed?

**Comment by abyss-w** [comment]
> @abyss-w can you help to fix the issue as discussed?

Yes. I can,

**Comment by Xuanwo** [comment]
Fixed in #66
