### ISSUE TITLE
refactor: evalSymlinks -> evalSymlink -> walkSymlinks doesn't make sense

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-service-fs#82]
```go
func evalSymlinks(path string) (string, error) {
	return evalSymlink(path)
}

func evalSymlink(path string) (string, error) {
	return walkSymlinks(path)
}

func walkSymlinks(path string) (string, error) {
	xxxxx
}
```

Can we reduce the extra layer?

**Comment by Xuanwo** [comment]
ping @JinnyYi for a look.

**Comment by JinnyYi** [comment]
There are differences in the implementation of `evalSymlink` on windows and unix platforms. So we have `evalSymlinks` -> `evalSymlink`, and `evalSymlink` implemented both in symlink_windows.go and symlink_unix.go.

**Comment by Xuanwo** [comment]
Can we implement `evalSymlinks` in `symlink_windows.go` and `symlink_unix.go` directly?
